modified Makefile so that I could compile. I am not sure why but I got a strange error concerning.
Warning: Reading file 'lsdaltonsrc/lsdalton_wrapper.o' as free form
lsdaltonsrc/lsdalton_wrapper.o:1.1:

\x7FELF\x02\x01\x01\x01>\x01\xF8\x04@@\x15\x12UH\x89\xE5\xB8\xE8]\xC3UH\x89\xE5H\x83\xEC\x10\x89}\xFCH\x89u\xF0H\x8BU\xF0\x8BE\xFCH\x89\xD6\x89\xC7\xE8\xBE\xBF\x08\xE8\xE8\xBC\xFF\xFF\xFF\xB8\xC9\xC3D\xFF\x03\x01\x01\x01\x01\x9D\x04\x08\x01\x0E\x02\x02\x01
 1
Error: Invalid character in name at (1)

TK