hjaaj. bugfix for pelib compilation under some circumstances.
- After last pelib upgrade USE_MPIF was always set FALSE.
  This is problematic because when I tried to build dalton.x I got this error message:

   [ 58%] Building Fortran object CMakeFiles/PElib.dir/src/pelib_mpi.F90.o
   /home/hjj/progs/gitDalton_hjaaj-srdft/external/pelib/src/pelib_mpi.F90:32:8:

        use mpi
           1
   Fatal Error: Cannot read module file ‘mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran
   compilation terminated.

- This happens sometimes. I have therefore restored that USE_MPIF is set to true in such cases.
- After this change dalton.x is again built without problems :-)